apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gcp-demo
  template:
    metadata:
      labels:
        app: gcp-demo
    spec:
      containers:
      - name: gcp-demo
        image: gcr.io/deep-tracer-426413-h4/go-gcp:latest
        ports:
        - containerPort: 8003
