# name: GKE Deploy
# on:
#   push:
#     branches:
#       - main
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout the repository
#       uses: actions/checkout@v3

#     - name: Authenticate to Google Cloud
#       uses: google-github-actions/auth@v1
#       with:
#         credentials_json: ${{ secrets.GCP_SA_KEY }}

#     - name: Set up Google Cloud SDK
#       uses: google-github-actions/setup-gcloud@v2
#       with:
#         project_id: gcp-demo-438911

#     - name: Configure Docker
#       run: gcloud auth configure-docker

#     - name: Build the Docker image
#       run: docker build -t gcr.io/gcp-demo-438911/gcp-demo:latest .

#     - name: Push the Docker image to GCR
#       run: docker push gcr.io/gcp-demo-438911/gcp-demo:latest

#     - name: Apply Kubernetes deployment
#       run: |
#         kubectl apply -f deployment.yaml
#         kubectl apply -f service.yaml
name: GKE Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: gcp-demo-438911

    - name: Configure Docker
      run: gcloud auth configure-docker

    - name: Build the Docker image
      run: docker build -t gcr.io/gcp-demo-438911/gcp-demo:latest .

    - name: Push the Docker image to GCR
      run: docker push gcr.io/gcp-demo-438911/gcp-demo:latest

    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: gcp-demo	
        location: us-east4         # Replace with the region (e.g., us-central1)
        project_id: gcp-demo-438911

    - name: Apply Kubernetes deployment
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
